import { Inter } from "next/font/google";
import { AuthContextProvider } from "./auth/auth-context";
import { createTheme , MantineProvider } from "@mantine/core";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const theme = createTheme({
  colorScheme: "light",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MantineProvider withGlobalStyles withNormalizeCSS theme={theme}>
      <AuthContextProvider>
        {children}
        </AuthContextProvider>
        </MantineProvider>
        </body>
    </html>
  );
}
