
POST http://localhost:3000/api/order/cancel-item HTTP/1.1
Content-Type: application/json

{
  "orderItemId": 820,
  "userId": "ftTlS3bbXnbha2zG5Sd68FLA3IF2",
  "cancellationReason": "Changed my mind about this item"
}


######


POST http://localhost:3000/api/order/update-shipping-cost HTTP/1.1
Content-Type: application/json

{
  "orderId": 185,
  "userId": "e7vVMBprlRYB7PHuaJgv2u2RAVb2",
  "newShippingCost": 177.50
}


######





GET http://localhost:3000/api/search?term=Cotton  HTTP/1.1

#######




POST http://localhost:3000/api/order/cancel-item HTTP/1.1
Content-Type: application/json

{
  "orderItemId": 820,
  "userId": "ftTlS3bbXnbha2zG5Sd68FLA3IF2",
  "cancellationReason": "Changed my mind about this item"
}




####
GET http://localhost:3000/api/search?term=Lavita HTTP/1.1


#######

GET http://localhost:3000//api/products/22



###
//Test for update product info
PUT http://localhost:3000/api/seller/11 HTTP/1.1
Content-Type: application/json

{
    "product_type": "yarn",
    "product_name": "Updated Product Name 1",
    "product_description": "Updated Product Description",
    "price": "15.00",
    "image_url": "https://firebasestorage.googleapis.com/v0/b/techtextile-ca673.appspot.com/o/images%2F5e751f0a-b3e1-46b3-842c-63ce259477d5%2F71kPl8i9nbL._AC_SX679_.jpg?alt=media&token=f3b47068-f47f-4586-aade-ba4edb425488,https://firebasestorage.googleapis.com/v0/b/techtextile-ca673.appspot.com/o/images%2F5e751f0a-b3e1-46b3-842c-63ce259477d5%2F71MYFAAEaEL._AC_SX679_.jpg?alt=media&token=56f6e6e2-8a52-4366-95b9-e310d0cb4678,https://firebasestorage.googleapis.com/v0/b/techtextile-ca673.appspot.com/o/images%2F5e751f0a-b3e1-46b3-842c-63ce259477d5%2F81dWwSKJCCL._AC_SX679_.jpg?alt=media&token=1b9914e3-9135-408d-93da-3f2dd2bc4e7c",
    "yarn_variants": [
        {
            "variant_id": 22,
            "color": "#ff5233",
            "denier": [
                { "denier": 11, "quantity": 60 }
            ]
        },
        {
            "variant_id": 23,
            "color": "#70ff7c",
            "denier": [
                { "denier": 12, "quantity": 50 }
            ]  
        }
    ]
}
###
//Test for SellerViewItem
GET http://localhost:3000/api/seller/LTdAf0Zzqvd6ZQhfNYBhUAn2m6s2 HTTP/1.1
### 
//Test Business Stats API
GET http://localhost:3000/api/sales/LTdAf0Zzqvd6ZQhfNYBhUAn2m6s2 HTTP/1.1
###
//Test for Purchased Item
GET http://localhost:3000/api/admin/LTdAf0Zzqvd6ZQhfNYBhUAn2m6s2 HTTP/1.1
###
GET http://localhost:3000/api/admin/e7vVMBprlRYB7PHuaJgv2u2RAVb2?status=cancled  HTTP/1.1
###
//For Product review
GET http://localhost:3000/api/productreviewforseller/e7vVMBprlRYB7PHuaJgv2u2RAVb2 HTTP/1.1
###




POST http://localhost:3000/api/email HTTP/1.1
Content-Type: application/json

{
  "userId": "12345",
  "shippingInfo": {
    "firstName": "John",
    "lastName": "Doe",
    "address": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip": "12345",
    "email": "john.doe@example.com"
  },
  "cart": [
    {
      "product_name": "T-Shirt",
      "quantity": 2
    },
    {
      "product_name": "Jeans",
      "quantity": 1
    }
  ],
  "selectedPaymentMethod": "Credit Card",
  "totalPrice": 100.00,
  "paymentInfo": {
    "cardNumber": "4111111111111111",
    "expiryDate": "12/24",
    "cvv": "123"
  }
}

POST http://localhost:3000/api/fedexApi HTTP/1.1
Content-Type: application/json

{
  "sellerAddress": {
    "street": "No 4 Shubhlaxmi Bunglows",
    "city": "Surat",
    "state": "GJ",
    "zipCode": "395017",
    "country": "IN"
  },
  "buyerAddress": {
   "street": "1919 University Dr NW",
    "city": "Calgary",
    "state": "AB",
    "zipCode": "T2N 4K9",
    "country": "CA"
  },
  "packages": [
    {
      "weight": 10,
      "length": 10,
      "width": 10,
      "height": 10
    }
  ]
}

 


####


PUT http://localhost:3000/api/cart/e7vVMBprlRYB7PHuaJgv2u2RAVb2 HTTP/1.1
content-type: application/json

 {
   "quantity": 3,
   "cartItemId": "70",
   "variantId": [70,78]
 }




# #####3






# #####4




#####

POST http://localhost:3000//api/review  HTTP/1.1
content-type: application/json

{
  "": "e7vVMBprlRYB7PHuaJgv2u2RAVb2",
  "rating": 5,
  "review": "This is a good product"
}
######



GET  http://localhost:3000/api/cart/ftTlS3bbXnbha2zG5Sd68FLA3IF2 HTTP/1.1

####
GET http://localhost:3000/api/search?term=LaVita HTTP/1.1
